import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Hello World",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex items-center justify-between p-2 bg-blue-600 text-white">
          <h2 className="text-3xl font-bold">Blogy</h2>
          <div className="space-x-4 underline">
          <Link href={"/create"}>Create new blog</Link>
          <Link href={"/about"}>About</Link>  
          </div>       
        </nav> 
        <div className="px-2">
         {children}
        </div>
       
      </body>
    </html>
  );
}
